Repository hmcts/version-reporter-services, pull requests merged in 2024-07, with the labels that each got.

#164 Adding additional provider for ptlsbox instead of using multiple stages.
  components/versionreporting/00-init.tf
  components/versionreporting/02-variabes.tf
  components/versionreporting/06-ptl-mi-access.tf
  components/versionreporting/06-ptlsbox-mi-access.tf
  components/versionreporting/07-keyvault.tf
Labels: Infrastructure/destroy

#165 DTSPO-17920: PlatOps Apps dashboard
  azure-pipelines.yaml
  components/versionreporting/02-variables.tf
  reports/platopsapps/.dockerignore
  reports/platopsapps/.gitignore
  reports/platopsapps/Dockerfile
  reports/platopsapps/README.md
  reports/platopsapps/cosmos_functions.py
  reports/platopsapps/entrypoint.sh
  reports/platopsapps/main.py
  reports/platopsapps/requirements.txt
  reports/platopsapps/set_env.sh
  reports/platopsapps/test_main.py
Labels: Infrastructure/add-or-update

#166 Fix: dockerfile syntax
  reports/platopsapps/Dockerfile
Labels: Infrastructure/no-changes

#150 DTSPO-17923- Backend work for Helm Chart app versions we manage
  .DS_Store
  reports/helmcharts/Dockerfile
  reports/helmcharts/entrypoint.sh
  reports/helmcharts/helm-chart-versions.sh
  reports/helmcharts/save-to-cosmos.py
  reports/helmcharts/set_env.sh
Labels: Infrastructure/no-changes

#171 Add requirements.txt
  reports/helmcharts/requirements.txt
Labels: Infrastructure/no-changes

#172 update readme.md for helmchart
  reports/helmcharts/README.md
Labels: Infrastructure/no-changes

#175 remove ensurepip from docker file
  reports/helmcharts/Dockerfile
Labels: Infrastructure/no-changes

#170 Adding latest version functions and comparisons with current for complete outputs
  reports/platopsapps/README.md
  reports/platopsapps/main.py
  reports/platopsapps/requirements.txt
  reports/platopsapps/test_main.py
  reports/platopsapps/test_version_utility.py
  reports/platopsapps/version_utility.py
Labels: Infrastructure/no-changes

#177 fix issue with service connection
  components/versionreporting/06-ptlsbox-mi-access.tf
  components/versionreporting/10-local.tf
Labels: Infrastructure/add-or-update

#173 Add terraform config for MI in all envs
  azure-pipelines.yaml
  components/managedidentity/.terraform-version
  components/managedidentity/00-init.tf
  components/managedidentity/02-variables.tf
  components/managedidentity/03-interpolated.tf
  components/managedidentity/04-managed-identities.tf
  components/managedidentity/05-keyvault.tf
  components/managedidentity/locals.tf
  components/versionreporting/05-cosmosdb.tf
  components/versionreporting/06-ptl-mi-access.tf
  components/versionreporting/06-ptlsbox-mi-access.tf
  components/versionreporting/07-keyvault.tf
Labels: Core_Infrastructure/destroy, Managed_Identity_Infrastructure_sbox/add-or-update, Managed_Identity_Infrastructure_demo/add-or-update, Managed_Identity_Infrastructure_test/add-or-update, Managed_Identity_Infrastructure_stg/add-or-update, Managed_Identity_Infrastructure_ithc/add-or-update, Managed_Identity_Infrastructure_dev/add-or-update, Managed_Identity_Infrastructure_prod/add-or-update, Managed_Identity_Infrastructure_ptl/add-or-update

#181 Update SDS cluster name
  reports/aksversions/main.py
Labels: Core_Infrastructure/no-changes, Managed_Identity_Infrastructure_sbox/no-changes, Managed_Identity_Infrastructure_dev/no-changes, Managed_Identity_Infrastructure_ptlsbox/no-changes, Managed_Identity_Infrastructure_stg/no-changes, Managed_Identity_Infrastructure_ithc/no-changes, Managed_Identity_Infrastructure_demo/no-changes, Managed_Identity_Infrastructure_test/no-changes, Managed_Identity_Infrastructure_ptl/no-changes, Managed_Identity_Infrastructure_prod/no-changes

#185 DTSPO-18384: Add role assignments to all MIS for cosmos
  components/managedidentity/04-managed-identities.tf
  components/versionreporting/00-init.tf
  components/versionreporting/05-cosmosdb.tf
  reports/renovate/save-to-cosmos.py
Labels: Managed_Identity_Infrastructure_sbox/add-or-update, Managed_Identity_Infrastructure_demo/add-or-update, Managed_Identity_Infrastructure_test/add-or-update, Managed_Identity_Infrastructure_stg/add-or-update, Managed_Identity_Infrastructure_ithc/add-or-update, Managed_Identity_Infrastructure_dev/add-or-update, Managed_Identity_Infrastructure_prod/add-or-update, Managed_Identity_Infrastructure_ptl/add-or-update, Core_Infrastructure/no-changes

#186 Fix: RG not found when adding role assignment
  components/managedidentity/04-managed-identities.tf
  components/versionreporting/05-cosmosdb.tf
Labels: Core_Infrastructure/destroy, Managed_Identity_Infrastructure_sbox/add-or-update, Managed_Identity_Infrastructure_demo/add-or-update, Managed_Identity_Infrastructure_test/add-or-update, Managed_Identity_Infrastructure_stg/add-or-update, Managed_Identity_Infrastructure_ithc/add-or-update, Managed_Identity_Infrastructure_dev/add-or-update, Managed_Identity_Infrastructure_prod/add-or-update, Managed_Identity_Infrastructure_ptl/add-or-update

#187 Update report so method is available
  reports/renovate/Dockerfile
  reports/renovate/save-to-cosmos.py
Labels: Core_Infrastructure/no-changes, Managed_Identity_Infrastructure_sbox/no-changes, Managed_Identity_Infrastructure_dev/no-changes, Managed_Identity_Infrastructure_ptlsbox/no-changes, Managed_Identity_Infrastructure_stg/no-changes, Managed_Identity_Infrastructure_ithc/no-changes, Managed_Identity_Infrastructure_demo/no-changes, Managed_Identity_Infrastructure_test/no-changes, Managed_Identity_Infrastructure_ptl/no-changes, Managed_Identity_Infrastructure_prod/no-changes

#190 add cosmos to managed-identity
  .DS_Store
  components/managedidentity/00-init.tf
  components/managedidentity/02-variables.tf
  components/managedidentity/04-managed-identities.tf
  components/managedidentity/locals.tf
Labels: Managed_Identity_Infrastructure_sbox/add-or-update, Managed_Identity_Infrastructure_demo/add-or-update, Managed_Identity_Infrastructure_test/add-or-update, Managed_Identity_Infrastructure_stg/add-or-update, Managed_Identity_Infrastructure_ithc/add-or-update, Managed_Identity_Infrastructure_dev/add-or-update, Managed_Identity_Infrastructure_prod/add-or-update, Managed_Identity_Infrastructure_ptl/add-or-update, Core_Infrastructure/no-changes
